### ISSUE TITLE
Adicionar lerna e transformar este repo em monorepo

### ISSUE THREAD

**Issue by atilacamurca** [comsolid/remote-pad#49]
Finalizar todos os merges pendentes nos outros repositórios e importar para este repositório.

### TODO

- [ ] converter este repositório em um lerna compatível
- [ ] (client) criar npm-script de watch para compilar cada vez que o código for modificado
- [ ] (server) importar remote-pad-server
- [ ] (server) criar npm-script de watch para compilar cada vez que o código for modificado
- [ ] (gui) importar remote-pad-gui
- [ ] (gui) modificar `cwd` ao instanciar o `forever.Monitor` para um diretório relativo à nova estrutura
